//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalogo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int idProd { get; set; }
        public int idCat { get; set; }
        public string nomeProd { get; set; }
        public string descProd { get; set; }
        public string imagem { get; set; }
    }
}
